---
deployment:
  tasks:
    - export DEPLOYPATH=/home/viernesgastronom/repositories/learning-log

    # Clonar el repositorio
    - echo "Clonando el repositorio..."
    - /usr/local/cpanel/3rdparty/bin/git clone https://github.com/Lumanet/learning-log.git $DEPLOYPATH

    # Cambiar a la rama especificada
    - echo "Cambiando a la rama main..."
    - cd $DEPLOYPATH
    - /usr/local/cpanel/3rdparty/bin/git checkout main

    # Instalar dependencias
    - echo "Instalando dependencias..."
    - /usr/local/bin/pip install -r requirements.txt

    # Ejecutar migraciones
    - echo "Ejecutando migraciones..."
    - /usr/local/bin/python3 manage.py migrate
