---
deployment:
  tasks:
    - export DEPLOYPATH=${CPANEL_BASEDIR}/${APPNAME}
    - echo "Iniciando despliegue en ${DEPLOYPATH}"

    # Cambiar al directorio del proyecto clonado
    - cd ${DEPLOYPATH}

    # Crear un entorno virtual (si aún no existe)
    - if [ ! -d "env" ]; then python3 -m venv env; fi

    # Activar el entorno virtual
    - source env/bin/activate

    # Instalar las dependencias del proyecto
    - pip install -r requirements.txt

    # Configurar el archivo de inicio de la aplicación
    - echo "python3 manage.py runserver 0.0.0.0:8000" > start.sh
    - chmod +x start.sh

    # Crear un archivo .htaccess para redirigir el tráfico a tu aplicación
    - |
      echo 'RewriteEngine On
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule ^(.*)$ http://127.0.0.1:8000/$1 [P,L]' > ${DEPLOYPATH}/.htaccess

    # Iniciar la aplicación
    - bash start.sh
